var n;String.prototype.includes||(String.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});Array.prototype.includes||(Array.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});var aa=Boolean,q=RegExp.prototype.test,ba=Array.prototype.includes;Array.prototype.concat.bind([]);var ca=Function.call.bind(Array.prototype.slice),da=Function.apply.bind(Array.prototype.push),t="undefined"==typeof browser;t&&(browser=chrome);
var w=navigator.userAgent.includes("Edge/"),ea=navigator.userAgent.includes("Edg/"),y=navigator.userAgent.includes("Firefox/"),fa=navigator.userAgent.includes("OPR/"),ga=navigator.userAgent.includes("YaBrowser/"),z,ha,A,ia,ka,la,ma=y?69:w?77:66,na=y?220:150,C=["127.0.0.1:1001","0.1.0.1:1001"],oa=t?"Chrome_RenderWidgetHostHWND":w?"Windows.UI.Core.CoreWindow":null,pa=/(?!)/,qa=["main_frame","sub_frame"],ra=["object","image"],sa=ra.concat("xmlhttprequest",w?"other":[]),ta=qa.concat(ra,"xmlhttprequest",
"other"),F=["*://*/*"],ua=["ftp://*/*"],va=F.concat(ua,"file:///*",t?"about:blank":[]),wa=F.concat(t?"about:blank":[]),xa=/\.([^.\\/]*?)(?:\.[0-9.]+)?$/,ya=/^v(\d+)\.(\d+)(?:b(\d+))?\b/,za=browser.runtime.getManifest(),Aa=browser.runtime.getURL("captured.html"),Ba=browser.runtime.getURL("").slice(0,-1),Ca=browser.extension.getBackgroundPage().location.href,Da=fa||ga,Ea=t||w,Fa=!y,Ga=t,Ha=za.permissions.includes("notifications")||null,Ia=q.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|moz-extension):/),
Ja=q.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i),Ka=q.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|html|plain))$/),La=q.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),Ma=q.bind(/^idmreg:|\bidman|\binternetdownloadmanager\b/i),Na=ba.bind([301,302,303,307,308]),Oa=ba.bind([301,302,303]),Pa=q.bind(/^(?:https?|socks[45])$/),Qa={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},Ra=[null,[115,111,112,113,114],[111,112],[112],
[]],Sa=[null,[-115,116,117,122,118,119,120,121,123],[113],[113],[111]],Ta={16:1,17:2,18:4,45:8,46:16},Ua={http:1,https:9,ftp:2,ftps:10,idmreg:12},Va={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ",
"application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/torrent":"TORRENT|BTT","application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ",
"application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT",
"application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V",
"video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF",
"image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
function H(a,b,c,d,e,f){if(a){var g=["MSG#",a,"#",b,"#",c,"#",d];this.u=a;this.type=b;this.D=c;this.h=d;this.b=e||[];this.o=g;if(e)for(a=0;a<e.length;a++)g.push(":",e[a]||0);if(f)for(var h in f)if(e=f[h],null!=e)if(g.push(",",h,"="),"string"==typeof e){b=a=e.length;for(c=0;c<b;)d=e.charCodeAt(c++),128<=d&&(2048<=d?(a+=2,d-55296&56320||c++):a++);g.push(a,":",e)}else e instanceof Blob?g.push(e.size,":",e):g.push(e)}else this.s=new FileReader}function Wa(){this.g=this.constructor.prototype.C++}
Wa.prototype.C=1;function Xa(a,b,c,d){this.id=a;this.b=b;c&&(this.f=c.toLowerCase());d&&(this.c=d)}Xa.prototype.a=0;function Ya(a,b,c){this.id=a+","+b;this.b=null==c||0>c?null:a+","+c}function Za(a){a.i||(a.o.push(";"),a.i=!0);return a.o.join("")}function $a(a){a.i||(a.o.push(";"),a.i=!0);return new Blob(a.o)}function ab(a,b,c){a.i?a.c(a):(b.a=c||0,b.b=0,a.s.onload=a.aa.bind(a,b),bb(a,b,0,50))}
H.prototype.aa=function(a){for(var b=this.s.result;;)switch(a.b){case 0:var c=b.split(",",2),d=c.shift().split(":",2),e=d.shift();if(!d.length){if(!c.length)return this.c(this);a.b=1}var f=e.length+1,d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.c(this);this.u=parseInt(d[1]);this.type=parseInt(d[2]);this.D=parseInt(d[3]);this.h=parseInt(d[4]);b=b.slice(f);a.a+=f;a.b++;break;case 1:d=b.split(",",2);e=d.shift();if(!d.length){d=b.split(";",2);if(2>d.length)return bb(this,a,b.length,100);a.b=
4}f=e.length+1;this.b=d=e.split(":");for(e=0;e<d.length;e++)c=d[e],d[e]=c.includes(".")?parseFloat(c):parseInt(c);b=b.slice(f);a.a+=f;a.b++;break;case 2:c=b.split(",",2);2>c.length&&(c=b.split(";",2));var d=c.shift().split(":",2),g=d.shift(),f=g.length,e=!1;if(d.length)f++;else{if(!c.length)return bb(this,a,b.length,25);e=!0}d=g.split("=",3);if(2!=d.length)return this.c(this);c=parseInt(d[0]);d=parseInt(d[1]);a.a+=f;a.b++;if(e){this[c]=d;b=b.slice(f);a.b++;break}a.f=c;a.c=d;b=a.c;f=a.a;a=a.slice(f,
f+b);a.size==b?this.s.readAsText(a):this.c(this);return;case 3:return this[a.f]=b,a.a+=a.c,a.b++,bb(this,a,0,21);case 4:switch(b[0]){case ",":a.b=2;b=b.slice(1);break;case ";":a.b++;break;default:return this.c(this)}a.a++;break;case 5:this.i=!0;this.l(this);a.size>a.a&&(b=new H,b.l=this.l,b.c=this.c,ab(b,a,a.a));return}};function bb(a,b,c,d){var e=b.a;c=e+c;b.size>c?a.s.readAsBinaryString(b.slice(e,c+d)):a.c(a)}
function I(){if(z){var a=this.constructor.prototype,b;for(b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.La=[];this.ja=!1;this.oa=this.G=null;this.o=!1;this.X=0;this.$=null;this.c={};this.g={};this.a={};this.A={};this.b={};this.s={};this.h={};this.f={};this.W={};this.I={};this.K={};this.K.Tb=[];this.Ja=0;this.l=this.Ra=!1;this.ra=!0;this.N=null;this.Ma=this.Qa=!1;this.nb=this.Pa=this.mb=1;this.L={};this.i=null;this.pa=1;this.Sa=0;this.C=this.u=null;this.Na=pa;this.H=[null,
{},{},{},{}];this.D=this.m=null;this.Y=Array(16);this.ba=0;this.Oa=null;this.qa=this.aa=!1;t&&browser.browserAction.disable();y&&browser.runtime.onInstalled.addListener(this.sb);browser.runtime.onMessage.addListener(this.tb);browser.windows.onCreated.addListener(this.fb);browser.windows.onRemoved.addListener(this.gb);browser.windows.onFocusChanged.addListener(this.Rb);browser.tabs.onActivated.addListener(this.Ib);browser.tabs.onUpdated.addListener(this.Lb);browser.tabs.onRemoved.addListener(this.Kb);
browser.tabs.onAttached&&browser.tabs.onAttached.addListener(this.Jb);this.Ia();this.wa();cb(this,!0)}}n=I.prototype;n.sb=function(a){a.version=za.version;this.lb=a};n.tb=function(a,b){38==a[0]&&browser.tabs.remove(b.tab.id)};
n.bb=function(a){if(a){var b=a.value;a=Qa[b.mode];var c,d;this.Y.fill(void 0);if(5==a&&(d=b.pacScript))d.data&&5E4<d.data.length?a=4:(c=d.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=d.url,this.Y.fill(!0);else if(7==a){b=b.rules;d=b.bypassList;c=J(this,b.singleProxy);if(!c){c=J(this,b.fallbackProxy);var e=J(this,b.proxyForHttp,1),f=J(this,b.proxyForHttps,9),b=J(this,b.proxyForFtp,2);e!=f||e!=b||e!=c&&c?(c=(e||"")+";"+(f||"")+";"+(b||"")+";"+(c||""),++a):
c=e}d&&d.length&&(c+=";"+d.join(","))}b=5>a?a.toString():c?a+":"+c:null;b!=this.m&&(this.m&&this.ua(),this.m=b)}};function J(a,b,c){if(b){var d=b.scheme||"http",e="https"==d;a=a.Y;c?a[c]=e:a.fill(e);if(Pa(d))return d+"://"+b.host+(b.port?":"+b.port:"")}}
function db(a,b,c,d){if(b){var e=b.type;if("direct"==e)return"0";"socks"==e&&(e="socks5");if(Pa(e)){var f="1:"+e+"://"+b.host+":"+b.port;"socks5"==e&&b.proxyDNS&&(f+="#");c||d||!(c=a.D)||(c=c.substr(c.indexOf(";")+1||c.length));c&&(f+=";"+c);d&&f&&(a.D=f);return f}}}
n.ua=function eb(b,c){if(void 0===b){if((Fa||Ga)&&this.o){var d=this.u;d||(c="http://"+(this.G?(new URL(this.G.url)).host:C[0]),d=c+"/status/204+IDM");b=new XMLHttpRequest;b.timeout=1E3;b.onreadystatechange=eb.bind(this,b,c);b.open("GET",d,!0);b.send()}}else 4==b.readyState&&(204!=b.status?this.u=this.C=null:c&&(this.u=c+"/status/204+IDM",this.C=Fa&&this.$?c+"/client/"+this.$:null))};
function cb(a,b){var c=a.c,d=a.L={};browser.contextMenus.removeAll();for(var e=0;e<fb.length;e++){var f=fb[e];if(f[0]&&(y?b||c[f[1]]:1)){var g=f[3].split(","),h;t&&1392508928<=z&&1409286144>z&&0<=(h=g.indexOf("frame"))&&g.splice(h,1);d[e]=browser.contextMenus.create({title:gb(f[2]),contexts:g,onclick:f[4].bind(a),documentUrlPatterns:f[5]||va,enabled:!0})}}}function hb(a,b,c,d,e){a=a.h;return b in a?a[b]:a[b]=new Xa(b,c,d,e)}
function ib(a,b){var c=a.f,d=b.id;c[d]!==b&&(c[d]=b,w&&(c[b.requestId]=b))}function jb(a,b,c,d,e){a=a.A;var f,g;L(b)?(f=b.frameId||0,g=b.parentFrameId,d||(d=b.tabId),e||b.requestId||(e=b.url)):f=b;b=d+","+f;d=a[b]||(a[b]=new Ya(d,f,g));null!=c&&(d.g=c);e&&"about:blank"!=e&&(d.j=e);return d}function M(a,b){return a.A[b.tabId+","+b.frameId]}function kb(a){var b=new Wa;return a.s[b.g]=b}function lb(a,b){var c=b instanceof Wa&&b.g,d=c?b:a.s[b];delete a.s[c||b];return d}
function ob(a,b){for(var c=a.H,d=1;d<c.length;d++){var e=c[d][101];if(e&&e.test(b))return d}return 0}
n.wa=function(){var a=this.X%(C.length+1);if(a<C.length)this.G=a=new WebSocket("ws://"+C[a]+"/?cid="+Math.random().toString().substr(2,9),"plugin.v3.internetdownloadmanager.com"),a.onopen=this.Ca,a.onclose=this.R,a.onmessage=this.Hb,1==a.readyState?this.Ca():3==a.readyState&&this.R();else{this.oa=a=browser.runtime.connectNative("com.tonec.idm");try{a.postMessage("")}catch(b){a=null}a?(a.onDisconnect.addListener(this.R),a.onMessage.addListener(this.wb),this.Ca()):this.R()}};
n.Ca=function(){this.o=!0;this.Pa=1;var a=[12,33,Da?1028:1031,0],b={};b[112]=A;b[113]=ha;b[114]=oa;b[125]=JSON.stringify(this.lb);if(587202560<=z){var c=browser.i18n.getUILanguage().replace("_","-");"sr"==c&&(c+="-Cyrl-CS");b[116]=c}O(this,2,1,Da?0:1024,a,b)};
n.R=function(){browser.runtime.lastError;this.G=this.oa=null;if(this.o){this.o=!1;this.W={};for(var a=this.La,b=0;b<a.length;b++){var c=a.splice(b--,1).pop(),d=c.splice(0,2).pop();w&&c.splice(1);d.removeListener.apply(d,c)}this.ja=!1;this.m=this.C=this.u=null;t&&browser.browserAction.disable();t&&this.l&&browser.downloads.setShelfEnabled(!0)}a=++this.X;b=C.length+1;c=a/b;120>c&&(1==c&&this.ra&&this.va(),!a||a%b?this.wa():window.setTimeout(this.wa,5E3*c))};
n.Hb=function(a){var b=new H;b.l=this.$a;b.c=this.R;ab(b,a.data)};n.wb=function(a){var b=new H;b.l=this.$a;b.c=this.R;ab(b,new Blob([a]))};function O(a,b,c,d,e,f,g){if(!a.o)return!1;var h=a.Pa++;b=new H(h,b,c,d,e,f);if(g)return g.open("POST",a.C+"?seq="+h,!1),g.send($a(b)),200==g.status;if(g=a.G)g.send($a(b));else try{a.oa.postMessage(Za(b))}catch(k){return a.R(),!1}d&1&&(a.W[h]=b);return!0}
function pb(a,b){if(b.b){var c=b.b[6],d=a.f[c];if(d)return d.c?b.a=d.a.id:null;var d=a.g,e;for(e in d)if(d[e].f==c)return b.a=e}e=b[6];var d=b[17],f=b[50],g=b[7],h=a.K,k=a.h,l=a.a,m,p,r;if((m=h[e])||(m=h[d]))return b.a=m.id;if(m=h[f])r=m.id;for(c in k){var h=k[c],v=h.c;if(v){if(v==e||v==d||v==f){m=h.b;if(g){var x=l[m.tabId];x&&x.j!=g&&(m=null)}if(m)return b.a=m.id}v==g&&(p=h.b.id)}}return r?b.a=r:p?b.a=p:null}
n.Ua=function qb(b,c,d,e){if(c)return e?(c=(d=e.shift())&&this.a[d.id])?b.a=c.id:null:null;if(null!=b.a)return b.a;if(b.b){var f=b.b[7];if(f&&this.g[f])return b.a=f}if(pb(this,b))return b.a;e=this.g;var g=b[50],h=b[7];for(f in e){c=e[f];if(c.j==g){b.a=f;break}null==b.a&&c.j==h&&(b.a=f)}if(null!=b.a)return b.a;h&&browser.tabs.query({url:h},qb.bind(this,b,!0,d));return null};
n.ya=function(a,b,c,d,e,f){var g=a.tabId,h=a.ea,k;if(void 0===b){f=new P(this,a,!0);b=a.c;if(null==a.v)if(a.b)browser.tabs.get(g,Q(f,2)),browser.windows.getLastFocused(Q(f,3));else if(c=this.a[g])a.v=c.v;null==h&&a.j?browser.webNavigation.getAllFrames({tabId:g},Q(f,5)):0<h&&null==b&&browser.webNavigation.getFrame({frameId:h,tabId:g},Q(f,4));if(R(f))return}else if(b&&(c&&0<=c.index?a.v=c.windowId:d&&(a.v=d.id),e&&(k=e.parentFrameId),f)){d=a.j;e=d.includes("#")&&S(d);for(var l=f.length-1;0<=l;l--)if(b=
f[l],c=b.j,!b.bc&&b.frameId&&(c==d||e&&c==e)){h=a.ea=b.frameId;k=b.parentFrameId;break}}if(null==h)a.j||a.postMessage([11,g,null,!0]);else{f=g+","+h;0<=k&&(a.c=g+","+k);if(b=this.A[f])a.f=b.f,a.g=b.c,a.a=b.g,(c=b.S)&&a.j!=c&&(a.S=c),a.c||(a.c=b.b),(k=this.f[a.f])&&!k.a&&(k.a=a);this.a[f]=a;g=[11,g,h,!a.j,a.a,a.g];(h=a.A)&&a.g&&(k=this.H[h],f=Sa[h],g.push(h),da(g,f.map(rb(k))));a.postMessage(g)}};
n.ha=function sb(b,c,d,e,f,g,h,k){var l=tb(b,!0);if(!l)return 0;if(1==l){if(!h)return T(b,sb.bind(this,b,c,d,e,f,g,!0)),-1;L(k)&&(k=U(k))}h=[l];var m={};m[6]=S(b,1==l);m[50]=c;m[7]=d;m[8]=e;m[100]=f;m[102]=g;m[51]=k;m[54]=navigator.userAgent;m[121]=y?this.D:this.m;O(this,14,1,0,h,m);return 3};
n.jb=function(a,b,c,d,e){if(!d){if(!a||!a.length)return;c||(c={});var f=new P(this,a,b,c,!0);c.ca&&!c.hb&&T(c.ca,Q(f,4));for(var g=0;g<a.length;g++)T(a[g][0],Q(f,5+g));if(R(f))return}e&&(c.hb=U(e));for(g=0;g<a.length;g++)a[g][5]=U(arguments[g+5]);var f=0,g=[0],h={8:4};h[54]=navigator.userAgent;h[7]=c.ca;h[110]=c.U;h[111]=c.hb;h[121]=y?this.D:this.m;1<a.length&&(O(this,15,1,0,[a.length],h),f=16,h={});for(var k;k=a.shift();)h[6]=k[0],h[100]=k[2],h[102]=k[3],h[50]=k[4],h[51]=k[5],O(this,14,1,f,g,h)};
function ub(a,b,c,d,e,f,g,h){if(!d||a.c[-8]){var k=a.a[b];if(k){var l=kb(a),m=l.g;l.tabId=b;l.A=k;l.W=c;l.m=0;l.Y=[];if(k=d&&!!e)l.ba=!0,l.ja=e,l.H=f,l.I=g,l.X=h,e.b||vb(a,e);(d=d&&a.c[12])?(d=d.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/\~/g,"(?:.*\\.)?"),d="^(?:http|https|ftp|ftps)://(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)"):d="^(?:http|https|ftp|ftps)://";l.G=wb(a,b,[12,m,c,k,d]);l.$=0;l.G||lb(a,m)}}}n.Ab=function(a,b,c,d){(a=lb(this,b))&&this.ha(a.K,a.L,a.ca,a.h,c,d)};
n.O=function(a,b,c){if(4294967295==a)this.i=null,c=!0;else{var d=this.h[a];if(d){c=d.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:d.a=3;window.setTimeout(this.O.bind(this,a,!1,!0),1E3);return}d.a=0;c=!0}}c&&O(this,8,1,32,[a])};function xb(a,b){var c=a.b[b];if(c&&c.fa){var d=c.border,e=c.scale;O(a,7,2,c.J?128:c.Aa?256:c.ma?512:0,[b,Math.round((c.na+d)*e),Math.round((c.Ga+d)*e),Math.round((c.width-d-c.Da)*e),Math.round((c.height-d)*e)])}}
function yb(a,b,c,d){var e=a.h[b];if(e){var f=256;2==e.a&&(d?(f|=128,e.a=1):f|=64);var g,h,k,l,m,p;if(c){g=c[0];h=c[1];k=c[2]||g+1;l=c[3]||h+1;m=c[4];if(c=e.b.l)g+=c[0],h+=c[1],k=Math.min(k+c[0],c[2]),l=Math.min(l+c[1],c[3]);if(e=a.a[e.b.tabId])p=e.s}O(a,9,1,f,[b,g,h,k,l,m,p])}}
n.ia=function(a){var b=this.b,c=[];if(a)(a=b[a])&&(a.J||a.M||c.push(a.w));else for(var d in b)a=b[d],a.J||a.M||c.push(a.w);if(c.length){b=[15,null,null];a={};var e=this.h;for(d in e){var f=e[d],g=f.b;if(f.a&&c.includes(g.tabId)){var h=this.a[g.tabId];h&&h.update&&(h.update=!1,h.postMessage([14]));f.f?(b[2]=d,g.b||vb(this,g,null,a),g.postMessage(b)):yb(this,d,null,!0)}}}};function zb(a,b){var c=a.b[b];c&&!c.M&&Ab(a,c.w,void 0)}
function Ab(a,b,c){var d=c?0:2;c=c?32:64;var e=a.h,f;for(f in e){var g=e[f];g.a&&g.b.tabId==b&&g.a!=d&&(g.a=d,O(a,8,1,c,[f]))}}function Bb(a,b,c,d){var e=a.ba,f=(e&b)!=((c?63:32)&b);a.ba=c?e|=b:e&=~b;f&&(c=a.c[-1],b=a.c[-2],c=a.aa=0!=c&&(e&c)==c,e=a.qa=0!=b&&(e&b)==b,a.Oa=(c||e)&&d||null)}
n.Ha=function(a,b,c,d){var e=this.b[a];if(e)if(d)e.a|=b,e.b|=c,e.M&&window.clearTimeout(e.M),e.M=window.setTimeout(this.Ha.bind(this,a),d);else{b|=e.a;c|=e.b;e.a=e.b=e.M=null;if(b){for(var f in this.g)b=this.g[f],b.v==a&&b.b&&(b.update=!0);browser.windows.get(a,this.V);browser.tabs.query({windowId:a,active:!0},this.V)}if(c){if((a=this.b[a])&&!a.M){a=a.w;c=this.h;for(var g in c)f=c[g],f.a&&f.b.tabId==a&&1==f.a&&O(this,8,1,1152,[g])}}else this.ia(a)}};
n.V=function(a,b){a instanceof Array&&(a=a.shift());if(a){var c=a.windowId||a.id,d=this.b[c];if(d){if(a.windowId){if(d.Ba&&Ia(a.url))return;d.w=a.id;a.width&&(d.Fa=a.width);a.height&&(d.Ea=a.height)}else{var e=b?d.scale=this.pa:d.scale,f="fullscreen"==a.state,g=!b&&f!=d.J;d.J=f;d.Aa="maximized"==a.state;d.ma="minimized"==a.state;w?(d.width=Math.round(a.width/e),d.height=Math.round(a.height/e),d.left=Math.round(a.left/e),d.top=Math.round(a.top/e)):(d.width=a.width,d.height=a.height,d.left=a.left,d.top=
a.top);g&&(f?zb(this,c):this.ia(c))}g=d.Fa;e=d.Ea;if(g&&e){var h=d.width,f=d.height;if(!d.Ba&&!d.ma){if(g>h||e>f)return browser.windows.get(c,this.V);d.Ba=!0}g=h-g;h=g/2;0<=h&&20>=h?(d.border=h,d.na=d.Da=0):(h=d.border,y||fa?d.na=g-2*h:d.Da=g-2*h);e=f-e-2*h;e<=na&&50<=e&&(d.Ga=e)}b||xb(this,c);return d}}};n.Vb=function(a,b,c,d){a.j=b;a.o=c;a.a&&!d&&(a.a=!1);null==a.ea&&this.ya(a)};n.Xb=function(a,b,c,d){(b=this.s[b])&&c&&(b[101]||b.f&&b.U&&b.f!=b.U||(b.f=c),b.U=c);a.s=d};
function vb(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],f;f=a[b.c];b=f){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(f)}for(f=e.pop();b=e.pop();f=b)d=b.pb,c[2]=d,c[3]=b.ea,c[4]=d?null:b.j,c[5]=d?null:b.S,f.postMessage(c)}function wb(a,b,c){a=a.a;b+=",";var d=0,e;for(e in a)e.startsWith(b)&&(a[e].postMessage(c),d++);return d}
n.la=function(a,b){var c={file:"content.js",runAt:"document_start",allFrames:!0},d;620756992<=z&&(c.matchAboutBlank=!0);654311424<=z&&!w&&b&&(c.frameId=b,y&&(c.allFrames=!1));if(a instanceof Array)for(;d=a.shift();)try{d.discarded||browser.tabs.executeScript(d.id,c,V)}catch(e){}else if(d=a)try{browser.tabs.executeScript(d.id||d,c,V)}catch(e){}};
function Cb(a,b,c,d){var e=17,f=[b.v,b.fa,b.width,b.height,b.left,b.top,b.scale],g={};b.Aa?e|=256:b.ma&&(e|=512);null!=c&&(e|=c?2048:1024);d&&(g[117]=d);O(a,6,2,e,f,g)}n.Ia=function Db(b,c){if(c)for(;c.length;){var d=c.shift(),e=this.V(d,!0)||this.fb(d,!0);Cb(this,e,d.focused,d.title)}else if(!b){d=Db.bind(this,!0);try{browser.windows.getAll({windowTypes:["normal","popup"]},d)}catch(f){browser.windows.getAll(d)}}};
n.kb=function Eb(b,c){if(void 0===b)return Fb("system.display",Eb.bind(this));if(b){if(!c)return browser.system.display.getInfo(null,Eb.bind(this,b));this.Sa=c[0].displayZoomFactor}};
n.xa=function(a,b){if(!this.o)return Gb(b.id,"cannot_contact_idm");var c=a.linkUrl,d=a.pageUrl,e=d;if(a.menuItemId==this.L[4])return browser.downloads.search({query:[c]},this.ob.bind(this,c));if(a.menuItemId==this.L[1])c=a.frameUrl,c&&"about:blank"!=c||(c=d,e=null);else if(!c){var c=a.srcUrl,f=this.a[b.id+","+a.frameId];if(f){var g=kb(this);g.tabId=b.id;g.A=f;g.K=c;g.L=e;g.ca=d;g.h=4;return f.postMessage([18,g.g,c])}}c&&this.ha(c,e,d,4)};
n.Ta=function(a,b){if(!this.o)return Gb(b.id,"cannot_contact_idm");ub(this,b.id,a.menuItemId==this.L[2])};n.ob=function(a,b){for(var c,d,e;c=b.pop();)c.exists&&"complete"==c.state?d||e||(e=c.referrer):(d||(d=c.referrer),browser.downloads.erase({id:c.id}));this.ha(a,d||e,null,4)};
n.Db=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){a.name=a.name.split(":").shift();var c=a.id;null==c&&(c=a.id=a.portId_||this.mb++);var d=b.id,e="top"==a.name;a.tabId=d;a.v=0>b.index?null:b.windowId;a.h=!0;a.i=!1;a.b=e;a.ea=e?0:a.sender.frameId;a.u=0;a.j=a.sender.url||e&&b.url||null;a.S=null;this.g[c]=a;e&&(this.a[d]=a);a.j&&(a.A=ob(this,(new URL(a.j)).hostname));a.onMessage.addListener(this.Eb.bind(this,a));a.onDisconnect.addListener(this.ga);this.ya(a)}};
n.ga=function(a,b,c){browser.runtime.lastError;if(a.h){c||(a.h=!1);var d=this.K,e=this.h,f=this.f,g=this.s,h,k,l;for(l in d)d[l]===a&&delete d[l];for(var m in e)if(h=e[m],h.b===a)h.a&&this.O(m),delete e[m];for(m in f)(k=f[m],k.a!==a||k.h)||(delete f[m],w&&delete f[k.id]);for(m in g)g[m].A===a&&delete g[m];this.Oa===a&&Bb(this,63,!1);if(!c)if(c=a.tabId+","+a.ea,delete this.g[a.id],delete this.a[c],a.b&&delete this.a[a.tabId],w&&!b)browser.tabs.executeScript(a.tabId,{code:"__idm_connect__ && __idm_connect__(); true;"},
V);else for(m in a=this.A,a)c==a[m].b&&delete a[m]}};
n.Eb=function(a,b){switch(b[0]){case 21:b[0]=a;this.Vb.apply(this,b);break;case 24:b[0]=a;this.Xb.apply(this,b);break;case 22:var c=this.a[a.tabId+","+b[2]];if(c){c.pb=b[3];var d=c.l=b[4];if(c=this.a[c.c])if(c=c.l)d[0]+=c[0],d[1]+=c[1],d[2]=Math.min(d[2]+c[0],c[2]),d[3]=Math.min(d[3]+c[1],c[3])}break;case 23:var d=a.v,c=a.tabId,e=b[1],f=b[2],g=b[4],h=this.b[d];if(e){if(e=lb(this,e)){var h=c==h.w&&!h.J,k=!f||!g;k&&(f=c);var l=b[7];l&&(e[101]||e.f&&e.U&&e.f!=e.U||(e.f=l),e.U=l);var l=hb(this,f,a,k?
null:b[5],k?null:b[6]),m=h&&!l.a;l.a=h?1:2;e instanceof H&&W(this,e,2,(h?128:64)|(k?512:0),d,c,f,e.f);k||(yb(this,f,g),m&&window.setTimeout(this.ia.bind(this,d),3E3))}}else b[3]?(this.O(f,!0),delete this.h[f]):g&&c==h.w&&!h.J&&yb(this,f,g,!0);break;case 25:hb(this,b[1],a,b[2],b[3]);break;case 26:ub(this,a.tabId,!0,!0,a,b[1],b[2],b[3]);break;case 27:if(d=this.s[b[1]]){c=d.tabId;f=d.Y;if(g=b[4])if("string"==typeof g&&(g=JSON.parse(g)),g instanceof Array){if(e=b[5])for(h=0;h<g.length;h++)g[h][4]=e;da(f,
g)}b[3]&&(d.m+=b[3]);b[6]&&(d.ca=b[6]);b[7]&&(d.U=b[7]);++d.$==d.G&&(lb(this,d),d.ba?(f=this.b[d.A.v])&&f.w==c&&d.m&&(g=d.X,e=f.border,h=f.scale,O(this,10,1,0,[4294967295,f.v,Math.round(d.H*g+(f.na+e)*h),Math.round(d.I*g+(f.Ga+e)*h),0,d.m]),this.i=c,wb(this,c,[13,!0])):f.length?this.jb(f,d.W,d):Gb(c,"cannot_find_links"))}break;case 28:this.O(4294967295);break;case 29:b[0]=a;this.cb.apply(this,b);break;case 30:b[0]=a;this.cb.apply(this,b);break;case 31:b[0]=a;this.yb.apply(this,b);break;case 32:b[0]=
a;this.Bb.apply(this,b);break;case 39:b[0]=a;this.zb.apply(this,b);break;case 33:b[0]=a;this.ub.apply(this,b);break;case 34:b[0]=a;this.xb.apply(this,b);break;case 35:b[0]=a;this.Ab.apply(this,b);break;case 36:b[0]=a;this.Sb.apply(this,b);break;case 37:b[0]=a,this.Gb.apply(this,b)}};
n.$a=function(a){var b=a.type,c=a.D,d=a.h,e=a.b,f;if(1==b){var g=e[0];if(f=this.W[g])b=f.type,delete this.W[g]}switch(b){case 3:0<=this.X&&(this.X=-1,this.ua());d=e[0];this.Qa=9>d;this.Ma=10<=d;this.$=e[6];if(d=e[4])d/=96,t&&(d=620756992>z?1:620756992<=z&&621284967>z?d:637534208<=z&&638078312>z?d:1.24<d?d:1),this.pa=d,this.Ia(),t&&this.Sa&&this.kb();Hb(this,e[5],a);this.ra&&this.va();break;case 4:f=this.c;this.l=!!(e[3]&2147483648);Hb(this,e[2],a);f[-9]=0<(d&64);f[-13]=0<(d&1024)||Da;f[-8]=0<(d&32);
f[-4]=0<(d&2);f[-11]=0<(d&256)||2>c;f[-12]=0<(d&512)||2>c;f[-1]=e[0];f[-2]=e[1];f[12]=a[12];f[17]=a[17];X(f,a,1);X(f,a,2);X(f,a,3);X(f,a,4);X(f,a,10);X(f,a,9,1);X(f,a,11,1);X(f,a,20,0,0);X(f,a,21,0,1);Ib(f,a,19);Ib(f,a,18,1,1);cb(this);this.ja||(this.ja=!0,t&&browser.browserAction.enable(),this.B(1,browser.runtime.onConnect,this.Db),this.B(1,browser.webNavigation.onCreatedNavigationTarget,this.Cb),this.B(1,browser.webNavigation.onCommitted,this.ab),this.B(1,browser.webNavigation.onHistoryStateUpdated,
this.vb),t&&this.B(1,browser.proxy.settings.onChange,this.bb),t&&browser.proxy.settings.get({},this.bb),t&&this.l&&browser.downloads.setShelfEnabled(!1),t&&this.l&&this.B(2,browser.downloads.onCreated,this.qb),t&&this.l&&this.B(2,browser.downloads.onDeterminingFilename,this.rb),e=ka?void 0:ta,a=["blocking"],d=t&&!la&&1207959552<=z?["extraHeaders"]:[],this.B(3,browser.webRequest.onBeforeRequest,this.eb,{urls:ua,types:qa},a),this.B(3,browser.webRequest.onBeforeRequest,this.eb,{urls:F,types:e},["requestBody"]),
this.B(3,browser.webRequest.onBeforeSendHeaders,this.Nb,{urls:F,types:e},["requestHeaders"].concat(a,d)),this.B(3,browser.webRequest.onHeadersReceived,this.Pb,{urls:F,types:e},["responseHeaders"].concat(a)),this.B(3,browser.webRequest.onResponseStarted,this.Qb,{urls:F,types:e}),this.B(3,browser.webRequest.onErrorOccurred,this.Ob,{urls:F,types:e}),(e=this.c[17])&&this.B(4,browser.webRequest.onBeforeRequest,this.Mb,{urls:e.split("|"),types:qa},a),browser.tabs.query({url:F},this.la));break;case 18:e=
e[0];if(4<=e)break;f=Ra[e];var d=this.H[e],h;for(h in a)(h=parseInt(h))&&(102==h||110<h&&150>h)&&(d[h]=f.includes(h)?RegExp(a[h]):a[h]);X(d,a,101,1);f=this.H.map(Jb(102)).filter(aa);this.Na=RegExp("^https?://(?:"+f.join("|")+")","i");1==e&&(d[-115]=a[115],d[122]||(d[122]="yt"));break;case 5:a=e[0];(e=this.b[a])?(d=0!=(d&128),e.J!=d&&(e.J=d)&&zb(this,a)):this.gb(a);break;case 6:if(d&4)break;a=f.b[0];e=e[1];if(d=this.b[a])d.fa=e,xb(this,a);break;case 8:a=e[0];e=d&32;if(4294967295==a)wb(this,this.i,
[13,!1]),this.i=null;else if(a=this.h[a])a.a=e?0:2;break;case 11:a=e[0];4294967295==a&&(ub(this,this.i,!0,!0),this.i=null);break;case 12:try{var k=a.b[5],l=a[4],e=4==k?2:3;if((1==k||2==k)&&pb(this,a)){if(this.c[3].test(l))1==k?e=6:k=4;else if(this.c[-4]||this.c[4].test(l))e=6;a[8]|=256}if(4==k)if(this.Qa&&!a.b[7])W(this,a,1);else{switch(a.b[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.ib(a)}else W(this,a,e)}catch(m){W(this,a,0)}break;case 13:a=f.b[0];d=f.b[5];
e=e[1];h=3==e;if(3>=d)f.h&128?Kb(this,a,h):Y(this,a,h);else if(5==d)if(e){if(a=(f=this.f[a])&&f.da){h=f.method;e=f.requestHeaders;if(d=f.g)(d=Lb(d,Z(e,"Content-Type")))||(h="GET");a.timeout=1E4;a.onreadystatechange=this.Fb.bind(this,a,f.id);a.open(h,f.url,!0);for(f=0;f<e.length;f++)h=e[f].name,c=h.toLowerCase(),c.startsWith("x-idm-")||(Ja(c)&&(h="X-IDM-"+h),a.setRequestHeader(h,e[f].value));a.send(d)}}else Mb(this,a);break;case 20:e=a[123];d=!e;a=[a.u,0,0,0];f={};y&&(h=this.D)&&(f[122]=h,d||(d=h.substr(2).split(";",
1).shift()==e));f[121]=this.m;O(this,1,1,d?2:4,a,f);break;case 22:this.Ka(e[0],e[1],a[131],a[130]);break;case 1:break;default:!f&&d&1&&O(this,1,1,0,[a.u,0,0,0])}};n.Ka=function Nb(b,c,d,e,f){if(!w&&null==Ha){if(void 0===f)return Fb("notifications",Nb.bind(this,b,c,d,e));Ha=f||!1}Ha&&(browser.notifications.create(b.toString(),{type:"basic",title:e||"",message:d,iconUrl:"images/logoSmall.png"},V),c&&window.setTimeout(browser.notifications.clear.bind(null,b.toString(),V),1E3*c))};
n.ib=function(a,b,c){try{if(null==a.a)if(!b){var d=new P(this,a,!0);this.Ua(a,null,d)||browser.windows.getLastFocused(Q(d,2));if(R(d))return}else if(c){var e=this.b[c.id],f=this.a[e&&e.w];f&&(a.a=f.id)}var g=this.g[a.a];if(!g)return W(this,a,0);var h;var k=a.g;k||(k=Wa.prototype.C++,a.g=k,this.s[k]=a);h=k;(f=this.a[g.tabId])&&f.postMessage([14,h]);g.b||vb(this,g,h);g.postMessage([15,h,null,a[6],a[17],a[50],a[31]])}catch(l){W(this,a,0)}};
function W(a,b,c,d,e,f,g,h){-1!=c&&(e=[b.u,c,e,g,f],f={},f[8]=b[8],h&&(f[110]=h),O(a,1,2,d|(0==c?4:2),e,f))}n.Cb=function(a){jb(this,a).a=!0};
n.ab=function(a,b){var c=a.tabId,d=a.frameId,e=a.url,f=a.transitionType,f=f&&f.endsWith("_subframe");this.N!=c||Ia(e)||(this.N=null);var g=this.a[c+","+d];if(g){if(this.i){var h=this.b[g.v];h&&h.w==this.i&&this.O(4294967295)}b?e!=g.j&&(this.ga(g,!1,!0),g.j=e,g.u++,g.postMessage([17,!1,g.g])):(this.ga(g,!0),f&&"about:blank"==g.j&&this.la(c,d))}else f&&"about:blank"==e?(jb(this,a),this.la(c,d)):(c=M(this,a))&&c.a&&(c.j||!b)&&(c.a=!1)};n.vb=function(a){return this.ab(a,!0)};
n.fb=function(a,b){var c=a.id,d={v:c,width:a.width,height:a.height,left:a.left,top:a.top,scale:this.pa,border:8,Ga:ma,na:0,Da:0,Aa:"maximized"==a.state,ma:"minimized"==a.state,J:"fullscreen"==a.state,Ea:0,Fa:0,w:0,Ba:!y,fa:null,M:null};this.b[c]=d;b&&(browser.tabs.query({windowId:c,active:!0},this.V),browser.tabs.query({windowId:c,url:F},this.Wb),browser.tabs.query({windowId:c,url:F},this.la));return d};n.Wb=function(a){for(var b;b=a.shift();)jb(this,0,!0,b.id,b.url)};
n.gb=function(a){O(this,5,1,32,[a]);delete this.b[a]};n.Rb=function(a){if(0<a){var b=this.b[a];b&&(b.fa||Cb(this,b,!0),(b=this.a[b.w])&&b.a&&(b.a=!1,browser.tabs.reload(b.tabId)),w&&this.Ha(a,!1,!0,500))}};n.Lb=function(a,b,c){var d=c.windowId,e=this.b[d];e&&(e.fa||Cb(this,e),e.w||this.V(c));"complete"==b.status&&(a=this.a[a])&&!a.i&&(a.i=!0,this.ia(d))};
n.Kb=function(a){var b=this.a,c=this.A,d=a+",";this.N==a&&(this.N=null);(a=b[a])&&this.ga(a,!0);for(var e in b)e.startsWith(d)&&this.ga(b[e],!0);for(var f in c)f.startsWith(d)&&delete c[f]};n.Ib=function(a){this.ba=0;this.i&&this.O(4294967295);var b=a.windowId;a=a.tabId;var c,d=this.a[a];d&&(d.v||(d.v=b),c=d.a)&&(d.a=!1);if(d=this.b[b]){var e=d.w;d.w=a;this.N==e&&(this.N=null,window.setTimeout(browser.tabs.remove.bind(null,e),250));Ab(this,e);browser.tabs.get(a,this.V);c||this.ia(b)}c&&browser.tabs.reload(a)};
n.Jb=function(a,b){var c=b.newWindowId,d=this.g,e;for(e in d)(e=d[e])&&e.tabId==a&&(e.v=c);Ab(this,a,!0)};n.cb=function(a,b,c){var d=a.tabId;a=a.v;var e=this.b[a];this.i&&this.O(4294967295);e&&e.w==d&&(b&&(e.Fa=b),c&&(e.Ea=c),Ab(this,d),this.Ha(a,b||c,!1,500))};n.yb=function(a,b,c){(b=Ta[b])&&Bb(this,b,c,a)};n.Bb=function(a,b,c){0==b&&Bb(this,32,c,a)};n.zb=function(a,b,c){a.m=b;a.C=c};n.ub=function(){Bb(this,63,!1)};
n.xb=function(a,b,c,d,e){b&&(b=a.f)&&(a=32,d=[b,null==d?(a|=16,-2):d],b={},b[110]=c,b[115]=e,O(this,16,1,a,d,b))};n.Sb=function(a,b,c){if(a=this.f[b]){b=[b,0];var d={};d[115]=c;O(this,16,1,48,b,d);a.ka=!1;a.Xa&&Y(this,a)}};n.Gb=function(a,b,c,d){O(this,19,2,0,[b,c,a.tabId,a.f],d)};function Mb(a,b){var c=a.f[b];if(c){var d=c.da;c.ka=!1;c.da=null;c.Xa&&Y(a,c);d&&d.abort()}}n.Fb=function(a,b){if(4==a.readyState){var c=[b,0],d={};200==a.status&&(d[115]=a.response);O(this,16,1,48,c,d);Mb(this,b)}};
function Ob(a,b){var c=a.c;if(!c[-9]||b.m)return 1;if(b.i)return 6;if(b.c&&c[-4])return 1;var d=b.C,e=b.D=Pb(d.pathname);return c[9].test(d.hostname)||c[19].test(d.href)?1:2==(b.b&7)&&(b.s||c[-13])?d.pathname.endsWith("/")||c[21].test(d.pathname)?1:c[1].test(e)||a.l&&!c[20].test(e)?4:1:6}
function Qb(a,b){if(b.f)return 6;if(b.i)return 3;var c=a.c,d=c[18],e=c[1],f=b.C,g=b.D,h=f.search?null:g,k=b.c,l=ra.includes(b.type),m=!b.s,p=!l&&d.exec(f.href);if(p)for(var r=d.Yb,v=d.$b,x=d.Zb,u=d.ac,d=1;d<p.length;++d)if(p[d]){var r=r[--d],G,p=0,D=r.includes("V")|r.includes("A");if(k&&!D&&!r.includes("S")||m&&r.includes("D"))return 1;r.includes("G")&&(G=!0,p|="GET"==b.method);r.includes("P")&&(G=!0,p|="POST"==b.method);if(G&&!p)break;var E,K,B;if(p=u[d]){p=p.exec(f.href);if(!p)break;f=x[d];if(x=
f.F)B=!0,K=p[x];if(x=f.T)B=!0,E=p[x]}E||(E=Pb(K)||r.includes("T")&&(B=!0,g)||v[d]);if(D)E&&(h=b.D=E),k||(k=b.c=!0);else if(E?e.test(E):!B)return b.A=16777224,4;break}return h&&(l&&c[2].test(h)||k&&c[4].test(h))?1:(y||a.C)&&(b.s||c[-13])&&!k&&h&&e.test(h)?(b.A=8,4):6}
function Rb(a,b){if(b.L)return a.P(6,b),6;var c=b.statusCode;if(200!=c&&206!=c)return 1;var d=Z(b.responseHeaders,"Content-Type"),e=Z(b.responseHeaders,"Content-Disposition"),f=Sb(d).toLowerCase(),c="attachment"==Sb(e).toLowerCase(),g=b.c,h=b.Ya;if(h&&!c&&"text/html"==f){if(b.h){var k=M(a,b);k&&(k.c=!0);a.P(5,b)}return 1}if(g?b.m:b.f)return 1;if(a.l&&h&&c)return 4;var l,m,p,r,v,x,u,G,D=a.c,h=b.C,E=h.hostname,K=h.pathname,e=(d=Tb(e,"filename")||Tb(d,"name"))&&Pb(d);if(d)if(e)b.G=d,u=G=!0;else if(!g)return 1;
G||(d=K.split("/").pop(),(e=b.D||Pb(d))&&e.toLowerCase()==f.split("/").pop()&&(u=!0));if(!u){var B=D[10].test(f),N=Va[f];N&&(N=N.split("|"),e&&N.includes(e)?u=!0:(g?B:e)||(e=N.shift(),u=!0));e&&!u&&(c||B||!N&&!La(e))&&(u=!0)}if(g){var N=ob(a,E),B=a.H[N],ja=K+h.search;switch(N){case 1:if(B[111].test(K))l=u=!0;else if(B[112].test(ja))m=!0;else if(B[115].test(ja)&&"application/json"==f)v=!0;else if(B[113].test(K)&&"application/x-www-form-urlencoded"==f||B[114].test(ja)&&"video/vnd.mpeg.dash.mpd"==f)p=
!0;break;case 2:(E=B[111].exec(ja)||B[111].exec(K))&&Ka(f)?(f=E[1]&&B[112].exec(b.a.j))&&E[1]!=f[1]||(p=!0):c&&"image"==b.type&&"MP4"==e&&(x=!0);break;case 3:"M4S"==e&&(u=!0),E==B[111]&&B[112].test(K)&&"application/json"==f&&(p=!0)}u&&("M3U8"==e||"F4M"==e||a.Ma&&"MPD"==e?p=!0:"F4F"==e&&(d.endsWith("Seg1-Frag1")||d.endsWith("Seg1-Frag2")||d.includes("Seg1-Frag2_"))&&(r=!0));"ASF"==e&&((f=Z(b.responseHeaders,"Content-Length"))&&102400>=parseInt(f)&&(x=!0),"DCLK-AdSvr"==Z(b.responseHeaders,"Server")&&
(x=!0))}if(x)return 1;u&&(g&&D[3].test(e)?l=!0:g&&D[4].test(e)?b.f=!0:!b.f&&D[1].test(e)&&(k=!0));if(l){var mb,nb;if(x=D[11])x.test(h.hostname)?l=!1:(mb=a.a[b.tabId])&&(nb=mb.j)&&x.test((new URL(nb)).hostname)&&(l=!1)}p||r?"POST"!=b.method||b.g?(m=new XMLHttpRequest,m.responseType=r?"blob":"text",b.da=m,m=!0):m=!1:v&&(m=b.ka=!0);if(!k&&!l&&!m)return 1;u&&(b.o=e);G&&(b.G=d);b.h|=m;b.A=l||m?256:16|(g?4096:0)|(G||c?0:8388608);return k?4:l?2:5}
n.P=function Ub(b,c,d,e,f,g){var h=c.url,k=c.b||tb(h),l=1==(k&7),m=c.requestHeaders;if(l&&!e&&null==f&&(g=Z(m,"Cookie"),null==g))return T(h,Ub.bind(this,b,c,d,null,!0)),!0;L(g)&&(g=U(g));var p=c.id,r=c.a&&c.a.id,v=c.timeStamp,x=d?Math.floor(d.timeStamp-v):null,u=c.A,G=c.responseHeaders;f=c.H;var D=d&&d.ip;d=0;3==Vb(D,".")?u|=33554432:2<Vb(D,":")&&(u|=4194304);k&16&&(u|=2097152);"POST"==c.method&&(u|=512);4>b&&(y||e)&&(d|=1);c.h&&c.da&&(d|=1);c.h&&5!=b&&(d|=32);c.c&&(d|=16);k=[p,r,Math.floor(v/1E3),
Math.floor(v%1E3*1E3),k&7,b];p={};p[6]=S(h,l&&4>b);p[17]=c.S;p[4]=c.o;p[100]=c.G;p[8]=u;p[129]=x;p[122]=this.m;p[11]=Wb(m);p[13]=Wb(G);p[18]=Wb(f);c.g&&(p[14]=Lb(c.g,Z(m,"Content-Type")));c.u&&(p[19]=Lb(c.u,Z(f,"Content-Type")));if(null==m){b=this.A;h=c.tabId+","+c.frameId;do h=(l=b[h])&&l.b,l=l&&l.j,"about:blank"==l&&(l=null);while(!l&&h);p[50]=l;p[51]=g;p[54]=navigator.userAgent}y&&(p[122]=db(this,c.proxyInfo,Z(m,"Proxy-Authorization")),p[55]=db(this,c.I,Z(f,"Proxy-Authorization")));if(c=this.a[c.tabId])p[7]=
c.j,p[110]=c.title;return O(this,13,1,d,k,p,e)};n.Z=function Xb(b,c,d,e,f){if(void 0===b)c.ta=e,c.sa=f,ib(this,c);else{e=this.C?new XMLHttpRequest:null;f=this.P(b,c,d,e);e&&(f=(e=f&&parseInt(e.getResponseHeader("x-idm-status")))?3==e:this.P(b,c,d));if(f)return Ea&&!d?void(c.za=!0):y?new Promise(Xb.bind(this,void 0,c,null)):Y(this,c,!0);c.f=!0}};
function Y(a,b,c){var d=a.f,e,f;if(L(b))e=b.id;else if(!(b=d[e=b]))return;if(c){if(b.Ya||b.Wa){var g=0<b.statusCode,h=g||!b.requestHeaders,k=M(a,b);k&&k.a&&"main_frame"==b.type?browser.tabs.remove(b.tabId):t&&h&&!b.Wa&&587202560<=z?f={redirectUrl:"javascript:void(0)"}:t&&g&&587202560>z?(f=[{name:"Connection",value:"close"},{name:"Content-Type",value:"multipart/related"},{name:"Content-Length",value:"0"}],f={responseHeaders:f}):w&&h?f={redirectUrl:Yb(b,k)}:Ga&&h&&(f={redirectUrl:a.u||Yb(b,k)})}f||
(f={cancel:!0});b.za=!0}(a=b.ta)&&void 0!==c&&(b.ta=b.sa=null,a(f||{}));if(c=b.sa)b.ta=b.sa=null,c();if(b.da||b.ka)return b.Xa=!0,f;delete d[e];w&&delete d[b.requestId];return f}n.qb=function(a){var b=this.c;(this.l||a.byExtensionId)&&b[-9]&&!this.qa&&tb(a.finalUrl||a.url,!0)&&(this.I[a.id]=a,browser.downloads.pause(a.id,V))};
n.rb=function(a,b){var c=a.id,d=this.I;if(!d[c])return!1;var e=this.c,f=a.finalUrl||(a.finalUrl=a.url),g=new URL(f),h=a.b=tb(f,!0),k=a.o=Pb(a.filename||g.pathname);if(!(a.i=this.aa)&&!this.l&&(!e[1].test(k)||e[9].test(g.hostname)||e[19].test(g.href)))return Kb(this,c);a.Ub=b;d[c]=a;if(1==h){if(!a.referrer){var c=this.g,d=this.b,l;for(l in c)if(e=c[l],e.j==f&&(a.referrer=e.o,(g=d[e.v])&&g.w==e.tabId))break}l=new P(this.Za,a);T(f,Q(l,1));a.url!=f&&T(a.url,Q(l,2));if(R(l))return a.Va=!0}return this.Za(a)};
n.Za=function(a,b,c){var d=Date.now(),d=[a.id,0,Math.floor(d/1E3),Math.floor(d%1E3*1E3),a.b,2],e={};e[6]=S(a.finalUrl);e[4]=a.o;e[103]=a.totalBytes||null;e[100]=a.filename||null;e[127]=a.mime||null;e[8]=a.i?2048:0;e[50]=a.referrer||null;e[51]=U(b);e[54]=navigator.userAgent;e[122]=this.m;a.finalUrl!=a.url&&(e[17]=S(a.url),e[56]=U(c));return O(this,13,1,129,d,e)||Kb(this,a.id)};
function Kb(a,b,c){var d=a.I[b];if(d){if(c)return browser.downloads.cancel(b,V),!0;d.Va&&(d.Va=!1,d.Ub());browser.downloads.resume(b,V);delete a.I[b]}return!1}n.Mb=function(a){var b=new URL(a.url);if(b.search.startsWith("?d=")){var c=this.a[a.tabId];this.ha("idmreg:"+b.href.substr(b.protocol.length),null,c&&c.j);Y(this,a.requestId);(b=M(this,a))&&b.a&&"main_frame"==a.type&&browser.tabs.remove(a.tabId);return{redirectUrl:Aa+"?register=1"}}};
n.eb=function(a){var b=a.type,c=a.tabId,d=a.frameId;if(!(ka&&!ta.includes(b)||0>c&&0==d)){var e=a.url,f=a.method,g=tb(e);if(g&&("GET"==f||"POST"==f)&&e!=this.u){var h=a.id=w?String(this.nb++):a.requestId,k=this.f[h],l=this.qa,m="POST"==f,f="image"==b,p=t&&0>c&&"other"==b,r=!p&&0>c&&0>d,v=0<c&&b.endsWith("_frame"),c=r?null:this.a[c+","+d];y&&m&&k&&Oa(k.statusCode)&&(a.method="GET",m=!1);v&&(d=jb(this,a,!1),d.f!=h&&(d.f=h,d.i=e,d.c=!1),d.h=m);if(c||v||r||p||k){if(!l&&m&&a.requestBody){h=a.requestBody;
if(m=h.raw)for(d=0;d<m.length&&(m[d].bytes||(m=null));d++);if(!(m||h.formData||t&&h.error))return}h=new URL(e);h.hash="";a.C=h;a.b=g;a.i=this.aa;a.m=l;a.Ya=v;a.Wa=p;a.K=r;a.c=r||sa.includes(b);a.f=f;a.h=this.Na.test(e);a.g=a.requestBody;a.a=c;a.s=g&8||(y?a.proxyInfo&&"https"==a.proxyInfo.type:this.Y[g]);k&&(a.id=k.id,a.a=c=k.a,a.i=k.i,a.m=k.m,a.S=k.S||k.url,a.H=k.H||k.requestHeaders,a.u=k.u||k.g,y&&(a.I=k.I||k.proxyInfo));if(a.c&&!f){b=this.K;for(g=b.Tb;30<=g.length;)delete b[g.shift()];b[e]=c;g.push(e)}switch(a.l=
Ob(this,a)){case 1:a.f=!0;case 6:ib(this,a);break;case 4:return this.Z(1,a)}}}}};
n.Nb=function(a){var b=this.f[a.requestId];if(b){var c=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.za){if(b.K&&!b.a&&(a=Z(c,"Referer"))){for(var d,e=Zb(this.g);(d=e.shift())&&d.j!=a;);b.a=d}y&&b.proxyInfo&&db(this,b.proxyInfo,Z(c,"Proxy-Authorization"),!0);if("POST"==b.method&&(!b.g||b.g.error&&0<Z(c,"Content-Length")))return Y(this,b);switch(b.l=Qb(this,b)){case 1:b.f=!0;break;case 4:return this.Z(1,b);case 3:return this.Z(3,b)}}}else if(0>a.tabId&&"xmlhttprequest"==a.type&&(a.initiator?
a.initiator==Ba:a.originUrl?a.originUrl==Ca:1)){b=a.requestHeaders;c={};d=!1;for(a=0;a<b.length;a++){var e=b[a],f=e.name.toLowerCase();f.startsWith("x-idm-")?c[f.substr(6)]=d=!0:"origin"==f&&e.value==Ba&&(c[f]=d=!0)}if(d){for(a=0;a<b.length;a++)e=b[a],f=e.name.toLowerCase(),c[f]?b.splice(a--,1):f.startsWith("x-idm-")&&(e.name=e.name.substr(6));return{requestHeaders:b}}}};
n.Pb=function(a){var b=this.f[a.requestId];if(b){var c=b.statusLine=a.statusLine,d=b.statusCode=a.statusCode||parseInt(c.split(" ",2).pop());if(b.za||204==d&&c.includes(" IDM "))return Y(this,b,!0);c=b.responseHeaders=a.responseHeaders;b.L=Na(d);if("image"==b.type&&(d=Z(c,"Content-Type"))&&d.toLowerCase().startsWith("image/"))return Y(this,b);"quic"==Z(c,"Client-Protocol")?b.b|=16:(d=Z(c,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=Z(c,"Transfer-Encoding")&&(b.b|=16);switch(b.l=Rb(this,
b)){case 1:return Y(this,b);case 4:return this.Z(2,b,a);case 3:return this.Z(3,b,a)}if(b.ka)return c.push({name:"X-IDM-Request-ID",value:b.id.toString()}),{responseHeaders:c}}};n.Qb=function(a){if(a.type.endsWith("_frame")&&(200==a.statusCode||304==a.statusCode)){var b=M(this,a);b&&(b.j=a.url,b.S=b.i)}if(b=this.f[a.requestId])2==b.l?this.P(4,b,a):5==b.l&&this.P(5,b,a),Y(this,b)};n.Ob=function(a){Y(this,a.requestId)};
n.va=function(a,b,c,d,e){function f(a){a&&(this.N=a.id)}var g=ea&&"llbjbkhnmlidjebalopleeepgdfgcpec"==browser.runtime.id&&"ngpampappnmepgilojfohadhhmbhlaek";if(void 0===a&&(this.ra=!1,a=new P(this,!0),browser.storage.local.get("version",Q(a,1)),(y?1124073472<=z:w?1073741824<=z:1)&&browser.extension.isAllowedIncognitoAccess(Q(a,2)),t&&browser.management.get("jeaohhlajejodfjadcponpnjgkiikocn",Q(a,3)),ea&&browser.management.get(g||"llbjbkhnmlidjebalopleeepgdfgcpec",Q(a,4)),R(a)))return;L(d)&&d.enabled&&
browser.management.setEnabled(d.id,!1);L(e)&&e.enabled&&browser.management.setEnabled(g||browser.runtime.id,!1);L(b)&&(b=b.version||"");if((g=za.version||"")&&g!=b&&null!=b&&(browser.storage.local.set({version:g}),d=this.Ja,e=this.Ra,!b||!d||e)){g="current="+escape(g);b&&(g+="&previous="+escape(b));d&&(g+="&manager="+(d?[d>>24&255,d>>16&255,d>>8&255,d&255].join("."):""));e&&(g+="&update=1");null!=c&&!c&&(g+="&incognito=1");y&&(g+="&mzffox=1");fa&&(g+="&opera=1");if(w||ea)g+="&msedge=1";browser.tabs.create({url:browser.runtime.getURL("welcome.html?"+
g)},f.bind(this))}};function Hb(a,b,c){null==b&&(b=(b=ya.exec(c[13]))?b[1]<<24|b[2]<<16|b[3]<<8:0);a.Ja=b||0;a.Ra=102825984>b}function Gb(a,b){var c=browser.i18n.getMessage(b);y?browser.tabs.executeScript(a,{code:'window.alert(unescape("'+escape(c)+'")); true;'},V):window.alert(c)}n.B=function(a,b,c){if(null!=b){var d=ca(arguments);if(y||w)d[2]=function(){return c.apply(null,arguments)};this.La.push(d);b.addListener.apply(b,d.slice(2))}};
function P(a,b){this.caller=a instanceof Function?a:arguments.callee.caller;this.f=a instanceof Function?null:a;this.b=ca(arguments,1);this.a=0;this.g=this.c=!1}function Q(a,b){a.a++;return a.h.bind(a,b)}function R(a){return a.a?a.c=!0:a.g?(a.caller.apply(a.f,a.b),!0):!1}P.prototype.h=function(a,b){browser.runtime.lastError;this.b[a]=b;0==--this.a&&(this.c?this.caller.apply(this.f,this.b):this.g=!0)};function gb(a){return browser.i18n.getMessage(a)||a}
function S(a,b){var c=a.lastIndexOf("#");c>a.indexOf("?")&&"!"!=a[c+1]&&(a=a.substr(0,c));b&&!Ma(a)&&(a="idmfc"+a);return a}function Yb(a,b){var c=a.a,d=b&&!b.h;w&&(c&&a.url==c.m||(d=!1));return Aa+(d?"?back=1":"?host="+(new URL(c&&c.j||a.url)).hostname)}function T(a,b){if(w&&a.startsWith("ftp:"))b([]);else{var c={url:a};ia&&(c.firstPartyDomain=null);browser.cookies.getAll(c,b)}}
function U(a){var b="";if(a&&a.length)for(var c=0;c<a.length;c++)b&&(b+="; "),b+=a[c].name,b+="=",b+=a[c].value;return b}function Wb(a){if(!a||!a.length)return null;for(var b="",c=0;c<a.length;c++)b+=a[c].name,b+=": ",b+=a[c].value,b+="\n";return b}function Z(a,b){if(!a)return null;b=b.toLowerCase();for(var c=0;c<a.length;c++)if(a[c].name.toLowerCase()==b)return a[c].value;return null}
function Tb(a,b){if(!a)return null;var c,d,e=a.split(";");for(b=b.toLowerCase();e.length;){var f=e.shift(),g=f.indexOf("=");if(0<g){var h=f.substr(0,g).trim().toLowerCase(),k="*"==h[h.length-1];if(k)h=h.substr(0,h.length-1).trimRight();else if(d)continue;if(h==b){f=f.substr(g+1).trim();g=f.length-1;if('"'==f[0]?'"'==f[g]:"'"==f[0]&&"'"==f[g])f=f.substring(1,g);if(k){if(f=f.split("'",3),k=f.shift().toLowerCase(),(g="utf-8"==k||"utf8"==k)||!d)if(c=unescape(f.pop()),d=k,g)break}else c=unescape(f)}}else 0>
g&&null==c&&f.trim().toLowerCase()==b&&(c="")}return c}function Sb(a){var b=/[;,]/;return a&&(a=a.split(b,1).shift().trim())&&!a.includes("=")&&unescape(a)||""}
function Lb(a,b){var c=a.raw;if(c){for(var d=String.fromCharCode,e="",f=0;f<c.length;f++){var g=c[f].bytes;if(!g)return null;for(var g=new Uint8Array(g),h=g.length,k=0;k<h;k++)e+=d(g[k])}return e}c=a.formData;if(!c)return null;f=Sb(b).toLowerCase();e=[];if(f&&"application/x-www-form-urlencoded"!=f)if("multipart/form-data"==f){(g=Tb(b,"boundary"))||(g="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in c)for(h=c[d],f=0;f<h.length;f++)e.push("--",g,'\r\nContent-Disposition: form-data; name="',
d,'"\r\n\r\n',h[f],"\r\n");e.push("--",g,"--\r\n")}else return null;else for(d in c)for(h=c[d],d=d.split(" ").map(encodeURIComponent).join("+"),f=0;f<h.length;f++)e.length&&e.push("&"),e.push(d,"=",h[f].split(" ").map(encodeURIComponent).join("+"));return e.join("")}function Pb(a){return(a=xa.exec(a))?a.pop().toUpperCase():""}function tb(a,b){var c=a.split(":",1).shift().toLowerCase(),c=Ua[c]||0;return b?c&7:c}
function $b(a,b){browser.runtime.lastError;if(void 0===a){var c=navigator.userAgent,d=c.match(/\b(?!(?:Safari|Chrome|Gecko)\/)\w+\/(\d+)(?:.(\d+))?(?:.(\d+))?(?:.(\d+))?\b(?!.*[()])/);if(c=y?d:c.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/)){z=c[1]<<24|c[2]<<22|c[3]<<8|c[4];ha=c[0];A=d?d[0]:c[0];t&&navigator.brave&&(A=A.replace("Chrome/","Brave/"));browser.runtime.getBrowserInfo&&browser.runtime.getBrowserInfo($b);try{y&&browser.privacy.websites.firstPartyIsolate.get({},$b)}catch(e){}if(d=browser.webRequest.ResourceType)if(d.MEDIA&&
(ta.push("media"),sa.push("media")),d.OBJECT_SUBREQUEST||(ka=y&&922746880>z))ta.push("object_subrequest"),sa.push("object_subrequest")}t&&browser.management.get("clhiejnehegdfknplplojohghjaklbae",$b.bind(this,{}))}else"version"in a?(c=a.version.split(/\D+/),z=c[0]<<24|c[1]<<22|c[2]<<8|c[3],ha=A=a.name+"/"+a.version,Ga=939524096>z):"value"in a?ia=a.value:b&&(la=!0,A=A&&A.replace("Chrome/","Epic/"))}
function X(a,b,c,d,e){if(b=b[c]||void 0)try{b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\."),b=e?b.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):b.replace(/\?/g,".").replace(/\*/g,".*?"),d&&(b=b.replace(/~/g,"(?:\\b[^.]+\\.)?")),b=RegExp("^(?:"+b+")$",e?"":"i")}catch(f){b=null}a[c]=b||pa}
function Ib(a,b,c,d,e){b=b[c];var f=[],g=[],h=[],k=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(d){for(var l=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");l.length;)f.push(l.shift()),g.push(l.shift());b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(e){for(var l=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,"$1").split("|"),
m=/<([A-Z]):(.*?)>/g,p={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"},r,v=0;l.length;++v)if(r=l.shift()){for(var x={},u=["^"],G="",D,E=1;D=m.exec(r);++E)x[D[1]]=E++,G=RegExp.rightContext,u.push(RegExp.leftContext,"(",D[2].replace(/\*/g,p[D[1]]||".%%?"),")");u.push(G,"$");h[v]=x;k[v]=RegExp(u.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(m,"(?:$2)")}b=b.replace(/\*/g,".%%?").replace(/%%/g,"*");b=d||e?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(K){b=null}a[c]=b||(b=
/(?!)/);d&&(b.Yb=f,b.$b=g);e&&(b.Zb=h,b.ac=k)}function Vb(a,b){var c=0;if(a)for(var d=0;0<=(d=a.indexOf(b,d));d++,c++);return c}function Fb(a,b){b&&browser.runtime.lastError||browser.permissions.request({permissions:[a]},b)}function V(a){browser.runtime.lastError;a;!0}var rb=Function.bind.bind(function(a){return this[a]}),Jb=Function.bind.bind(function(a){return a&&a[this]}),L=Object.isExtensible;try{L(null)}catch(a){L=function(b){return b instanceof Object}}var Zb=Object.values;Zb||(Zb=function(a){return Object.keys(a).map(rb(a))});
String.prototype.startsWith||(String.prototype.startsWith=function(a,b){return this.substr(b||0,a.length)===a});String.prototype.endsWith||(String.prototype.endsWith=function(a,b){b=(null==b||b>this.length?this.length:b)-a.length;return 0<=b&&this.lastIndexOf(a,b)==b});Array.prototype.fill||(Array.prototype.fill=function(a){for(var b=this.length;b--;)this[b]=a;return this});
var fb=[[!0,-11,"menu_download_link","link,image",I.prototype.xa],[!0,-11,"menu_download_link","page,frame,editable",I.prototype.xa,wa],[!0,-11,"menu_download_selected","selection",I.prototype.Ta],[!0,-12,"menu_download_all","page,frame,editable",I.prototype.Ta],[t,-11,"menu_download_item","link",I.prototype.xa,["chrome://downloads/*"]]];$b();new I;

